### ISSUE TITLE
Segmentation fault on lsquic_engine_destroy

### ISSUE THREAD

**Issue by sergePSE** [litespeedtech/lsquic-client#37]
May I ask you for a hint in the next issue or maybe an advice, what can be additionally checked?
Segmentation fault: lsquic_full_conn.c:762
if (conn->fc_conn.cn_enc_session)
        conn->fc_conn.cn_esf->esf_destroy(conn->fc_conn.cn_enc_session);

conn->fc_conn.cn_esf does not exist, while conn->fc_conn.cn_enc_session exists.
Error appears after https://github.com/sergePSE/thesis_share/blob/master/quic_probe/src/quic_engine_holder.c:110

**Comment by dtikhonov** [comment]
> conn->fc_conn.cn_esf does not exist, while conn->fc_conn.cn_enc_session exists

This likely means indicates that contents of memory pointed to by `conn` are invalid.  This is because `cn_esf` is only assigned once, in the constructor.  On the other hand, the call to destroy `cn_enc_session` is pretty far down in the destructor, so all preceding cleanup function calls were OK.  Perhaps something fishy is done in the `on_conn_closed` callback?

I would try tracing the connection lifetime: `-l conn=debug`.

**Comment by sergePSE** [comment]
Thanks for response, debugging level was helpful and I've done a mistake in mentioned by you callback.
